# [Info]
site_name: 杨希杰的个人网站 # 左上角标题
site_url: https://yang-xijie.github.io
site_author: 杨希杰
site_description: 杨希杰的个人网站

# [Navigtion]
nav:
  - 讲稿:
    - LECTURE/index.md 
    - Linux:
      - Linux讲座: LECTURE/Linux/linux.md
      - 命令行入门精简版: LECTURE/Linux/commands-concise.md
    - Markdown:
      - Markdown讲座: LECTURE/Markdown/markdown.md
      - VSCode及插件安装: LECTURE/Markdown/vscode-extension.md
    - Git:
      - Git: LECTURE/Git/git.md
      - Git例子: LECTURE/Git/git-demos.md
      - Git合作: LECTURE/Git/git-teamwork.md
      - Windows安装Git: LECTURE/Git/windows-install.md
    - 应用开发设计: LECTURE/App/app-design.md
    - Flutter学习教程:
      - LECTURE/Flutter/221120-consideration.md
    - 在macOS上用VSCode写C++代码:
      - 0 介绍: LECTURE/vscode-cpp/0_about.md
      - 1 前言和课程说明: LECTURE/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: LECTURE/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: LECTURE/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: LECTURE/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: LECTURE/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: LECTURE/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: LECTURE/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: LECTURE/vscode-cpp/8_课程回顾.md
      - 其他: LECTURE/vscode-cpp/9_others.md
      - 极速版: LECTURE/vscode-cpp/10_极速版.md
      - 补充: LECTURE/vscode-cpp/11_补充.md
    - 英语音标教学: LECTURE/English/phonetic-symbol.md
    - 魔方:
      - LECTURE/Cube/basic.md
  - 博客:
    - BLOG/index.md
    - BLOG/others.md
    - CG:
      - BLOG/ComputerGraphics/cg-notes.md
      - BLOG/ComputerGraphics/games101.md
      - BLOG/ComputerGraphics/blender-notes.md
    - 游戏:
      - BLOG/Game/unity-notes.md
      - BLOG/Game/ue-notes.md
      - BLOG/Game/what-is-game.md
      - BLOG/Game/2d-vs-3d.md
      - BLOG/Game/controller.md
    - 日语:
      - BLOG/Japanese/notes-2202-2203.md
      - BLOG/Japanese/notes-2204.md
      - BLOG/Japanese/notes-2205.md
      - BLOG/Japanese/verb.md
      - BLOG/Japanese/adj.md
      - BLOG/Japanese/noun.md
      - BLOG/Japanese/grammar.md
      - BLOG/Japanese/essays.md
      - BLOG/Japanese/tantanmen-translation.md
      - BLOG/Japanese/chinese.md
    - OS:
      - BLOG/OS/fork-exec-spawn.md
      - BLOG/OS/fork-example.md
    - Linux:
      - BLOG/Linux/vim.md
      - BLOG/Linux/tmux.md
      - BLOG/Linux/unix.md
      - BLOG/Linux/kernel-compile.md
      - BLOG/Linux/pi-start.md
    - macOS:
      - BLOG/macOS/tree.md
      - BLOG/macOS/zoom.md
      - BLOG/macOS/sharing-mac-android.md
      - BLOG/macOS/mad.md
      - BLOG/macOS/stream.md
      - BLOG/macOS/intel-windows.md
    - 显示器:
      - BLOG//Display/sony-extend.md
    - Apple:
      - BLOG/Apple/mac-recommend.md
      - BLOG/Apple/ipad-recommend.md
    - GitHub:
      - BLOG/GitHub/mirror.md
    - Markdown:
      - BLOG/Markdown/grammars.md
      - BLOG/Markdown/mkdocs-site.md
      - BLOG/Markdown/mdbook-site.md
      - BLOG/Markdown/github-pages.md
    - 电子工程:
      - BLOG/ElectronicEngineering/verilog-simulation.md
      - BLOG/ElectronicEngineering/storage.md
      - BLOG/ElectronicEngineering/rlc.md
      - BLOG/ElectronicEngineering/yosys-try.md
    - FPGA:
      - BLOG/Fpga/compare.md
    - 基础:
      - 数学:
        - BLOG/Foundation/Math/latex.md
        - BLOG/Foundation/Math/linear.md
        - BLOG/Foundation/Math/taylor.md
        - BLOG/Foundation/Math/max-pr.md
        - BLOG/Foundation/Math/sympy-det.md
      - 物理:
        - BLOG/Foundation/Physics/guass-stokes.md
        - BLOG/Foundation/Physics/electromagnetics.md
      - 网络:
        - BLOG/Network/learning.md
        - BLOG/Network/nouns.md
      - 机器学习:
        - BLOG/Deeplearning/d2l.md
        - BLOG/Deeplearning/speech-recognition.md
        - BLOG/Deeplearning/parallel-load.md
        - DDP:
          - BLOG/Deeplearning/ddp.md
          - BLOG/Deeplearning/ddp-note.md
    - 其他:
      - BLOG/Others/video-info.md
  - 开发:
    - DEV/index.md
    - React:
      - DEV/React/notes.md
    - Three:
      - DEV/Three/setup.md
    - WebGPU:
      - DEV/Webgpu/articles.md
    - Flutter:
      - DEV/Flutter/commands.md
      - DEV/Flutter/template.md
      - DEV/Flutter/dart-lint.md
      - DEV/Flutter/state-management.md
      - DEV/Flutter/web-consideration.md
    - 编程:
      - DEV/Programming/recommendation.md
      - DEV/Programming/my-feelings.md
      - Python:
        - DEV/Programming/Python/copy.md
        - DEV/Programming/Python/numpy-overview.md
      - Dart:
        - DEV/Programming/Dart/learning.md
      - Swift:
        - DEV/Programming/Swift/learning-resources.md
        - DEV/Programming/Swift/notes-basic-grammars.md
        - DEV/Programming/Swift/notes-language-guide.md
        - DEV/Programming/Swift/notes-useful-foundation.md
        - DEV/Programming/Swift/lecture-homework.md
        - DEV/Programming/Swift/parallel-for.md
      - C:
        - DEV/Programming/C/review.md
        - DEV/Programming/C/final.md
        - DEV/Programming/C/stdout-fflush.md
        - DEV/Programming/C/watch-matrix.md
  - 二次元:
    - 2/index.md
    - 番:
      - 2/Anime/anime-rating.md
      - 2/Anime/anime-rating-extraordinary.md
      - 2/Anime/anime-rating-great.md
      - 2/Anime/anime-rating-good.md
      - 2/Anime/new-anime-criterion.md
    - 喜欢的:
      - 2/Sukina/pictures.md
      - 2/Sukina/kawaii.md
      - 2/Sukina/artists.md
      - 2/Sukina/vtuber.md
      - 2/Sukina/voice.md
    - Galgame:
      - 2/Galgame/ddlc.md
    - 原神:
      - 2/Games/Genshin/characters.md
      - 2/Games/Genshin/graphic-quality.md
      - 2/Games/Genshin/controller.md
      - 2/Games/Genshin/food.md
    - 狂野飙车9:
      - 2/Games/A9/start.md
      - 2/Games/A9/hoshii.md
    - Apex:
      - 2/Games/Apex/controller-aim.md
      - 2/Games/Apex/controller-settings.md
      - 2/Games/Apex/zhidong-settings.md
      - 2/Games/Apex/key-mouse-settings.md
      - 2/Games/Apex/characters.md
      - 2/Games/Apex/17.md
  - 转载:
    - REPRODUCE/index.md
    - REPRODUCE/how-to-ask-questions-the-smart-way.md
    - REPRODUCE/tim-cook-at-duke.md
    - REPRODUCE/my-best-teacher.md
    - REPRODUCE/kasi/watagumo.md
    - REPRODUCE/proses.md
    - REPRODUCE/poems.md
  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - WEBSITE/build.md
    - WEBSITE/help.md
    - WEBSITE/test.md
  - 随笔:
    - ESSAY/index.md
    - 随笔记:
      - ESSAY/Jottings/2307.md
      - ESSAY/Jottings/2306.md
      - ESSAY/Jottings/2305.md
      - ESSAY/Jottings/2304.md
      - ESSAY/Jottings/2303.md
      - ESSAY/Jottings/2302.md
      - ESSAY/Jottings/2301.md
      - ESSAY/Jottings/2211-2212.md
      - ESSAY/Jottings/2209-2210.md
      - ESSAY/Jottings/2207-2208.md
      - ESSAY/Jottings/2205-2206.md
      - ESSAY/Jottings/2203-2204.md
      - ESSAY/Jottings/2201-2202.md
      - ESSAY/Jottings/2111-2112.md
      - ESSAY/Jottings/2109-2110.md
      - ESSAY/Jottings/2107-2108.md
      - ESSAY/Jottings/2105-2106.md
      - ESSAY/Jottings/2103-2104.md
      - ESSAY/Jottings/2101-2102.md
      - ESSAY/Jottings/2011-2012.md
      - ESSAY/Jottings/2009-2010.md
      - ESSAY/Jottings/2007-2008.md
      - ESSAY/Jottings/2005-2006.md
      - ESSAY/Jottings/2003-2004.md
      - ESSAY/Jottings/2001-2002.md
      - ESSAY/Jottings/0.md
      - ESSAY/Jottings/1906-1912.md
      - ESSAY/Jottings/1807-1812.md
      - ESSAY/Jottings/1801-1806.md
      - ESSAY/Jottings/17.md
      - ESSAY/Jottings/16.md
    - 文章:
      - ESSAY/Articles/230629-account-book.md
      - ESSAY/Articles/230403-buy-phone.md
      - ESSAY/Articles/230305-cccc-memory.md
      - ESSAY/Articles/221227-expressvpn-refund.md
      - ESSAY/Articles/220921-upgrade-introduction.md
      - ESSAY/Articles/220715-macbook-story.md
      - ESSAY/Articles/220624-gratitude.md
      - ESSAY/Articles/220621-bytedance-interview.md
      - ESSAY/Articles/220612-reply.md
      - ESSAY/Articles/2205-good-games.md
      - ESSAY/Articles/220506-stop-jianshu.md
      - ESSAY/Articles/220505-library-thu.md
      - ESSAY/Articles/220415-interestx2.md
      - ESSAY/Articles/220410-job-discussion.md
      - ESSAY/Articles/220410-independence.md
      - ESSAY/Articles/220408-appreciating-girl.md
      - ESSAY/Articles/220402-languages-comparision.md
      - ESSAY/Articles/220324-thoughts-996.md
      - ESSAY/Articles/220107-want-to-be.md
      - ESSAY/Articles/211104-emotion-bad.md
      - ESSAY/Articles/210928-apple-recruitment-share.md
      - ESSAY/Articles/2109-covid-influence.md
      - ESSAY/Articles/2109-group-clear.md
      - ESSAY/Articles/210820-cccc-event.md
      - ESSAY/Articles/210801-affection-3.md
      - ESSAY/Articles/210519-app-dev-experience.md
      - ESSAY/Articles/210516-apple-education-address.md
      - ESSAY/Articles/210502-extend-your-way.md
      - ESSAY/Articles/201119-a-new-review.md
      - ESSAY/Articles/201213-look-at-yourself.md
      - ESSAY/Articles/200916-my-pursue.md
      - ESSAY/Articles/200713-sutuo-and-me.md
      - ESSAY/Articles/200703-talk-with-junior.md
      - ESSAY/Articles/200607-gaokao-memory.md
      - ESSAY/Articles/200604-small-goal.md
      - ESSAY/Articles/200602-tennkinoko.md
      - ESSAY/Articles/200506-why.md
      - ESSAY/Articles/2005-travel.md
      - ESSAY/Articles/190730-tangyan-rd-23.md
      - ESSAY/Articles/190723-feelings-in-6-days.md
      - ESSAY/Articles/190707-address-to-nonlocal-students.md
      - ESSAY/Articles/190629-affection-2.md
      - ESSAY/Articles/1905-non-intelligent.md
      - ESSAY/Articles/1901-go-to-thu.md
      - ESSAY/Articles/1811-do-it.md
      - ESSAY/Articles/1808-ideality-and-reality.md
      - ESSAY/Articles/1806-apply-thu.md
      - ESSAY/Articles/18-tree.md
      - ESSAY/Articles/18-what-i-love.md
      - ESSAY/Articles/17-dream-2017.md
      - ESSAY/Articles/14-affection-1.md
  - 我:
    - ME/index.md
    - ME/cv-full.md
    - ME/credentials.md
    - ME/curriculum-thu.md
    - ME/idea.md
    - ME/necessary-things-in-life.md
    - ME/create-family.md
    - ME/support.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Yang-Xijie/yang-xijie.github.io # 右上角点击跳转的链接
repo_name: yang-xijie.github.io # 右上角的名字
## [bottom-left corner]
copyright: 杨希杰 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
      name: Bilibili | 杨希杰619 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Yang-Xijie
      name: GitHub | Yang-Xijie

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
