# [Info]
# 左上角标题
site_name: 杨希杰的个人网站
site_url: https://yang-xijie.github.io
site_author: 杨希杰
site_description: 杨希杰的个人网站

# [Navigtion]
nav:
  - 我:
    - ME/index.md
    - ME/introduction.md
    - ME/profile.md
    - ME/contact.md
    - ME/account.md
    - ME/qq-groups.md
    - ME/description.md
    - ME/ability.md
    - ME/experience.md
    - ME/thu-curriculum.md
    - ME/thu-certificate.md
    - ME/daily-necessities.md
    - ME/support.md
  - 讲稿:
    - LECTURE/index.md
    - Linux:
      - Linux讲座: LECTURE/Linux/linux.md
      - 命令行入门精简版: LECTURE/Linux/commands-concise.md
    - Markdown:
      - Markdown讲座: LECTURE/Markdown/markdown.md
      - VSCode及插件安装: LECTURE/Markdown/vscode-extension.md
    - Git:
      - Git: LECTURE/Git/git.md
      - Git例子: LECTURE/Git/git-demos.md
      - Git合作: LECTURE/Git/git-teamwork.md
      - Windows安装Git: LECTURE/Git/windows-install.md
    - 应用开发设计: LECTURE/App/app-design.md
    - 在macOS上用VSCode写C++代码:
      - 0 介绍: LECTURE/vscode-cpp/0_about.md
      - 1 前言和课程说明: LECTURE/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: LECTURE/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: LECTURE/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: LECTURE/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: LECTURE/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: LECTURE/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: LECTURE/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: LECTURE/vscode-cpp/8_课程回顾.md
      - 其他: LECTURE/vscode-cpp/9_others.md
      - 极速版: LECTURE/vscode-cpp/10_极速版.md
      - 补充: LECTURE/vscode-cpp/11_补充.md
    - 英语音标教学: LECTURE/English/phonetic-symbol.md
    - 魔方:
      - LECTURE/Cube/basic.md
  - 博客:
    - BLOG/index.md
    - BLOG/others.md
    - Apple:
      - BLOG/Apple/mac-recommend.md
      - BLOG/Apple/ipad-recommend.md
    - macOS:
      - BLOG/macOS/tree.md
      - BLOG/macOS/zoom.md
      - BLOG/macOS/sharing-mac-android.md
      - BLOG/macOS/mad.md
      - BLOG/macOS/stream.md
      - BLOG/macOS/intel-windows.md
    - Markdown:
      - BLOG/Markdown/grammars.md
      - BLOG/Markdown/mkdocs-site.md
      - BLOG/Markdown/mdbook-site.md
      - BLOG/Markdown/github-pages.md
    - Linux:
      - BLOG/Linux/vim.md
      - BLOG/Linux/tmux.md
      - BLOG/Linux/unix.md
      - BLOG/Linux/kernel-compile.md
      - BLOG/Linux/pi-start.md
    - OS:
      - BLOG/OS/fork-exec-spawn.md
      - BLOG/OS/fork-example.md
    - 计算机网络:
      - BLOG/Network/learning.md
      - BLOG/Network/nouns.md
    - 数学:
      - BLOG/Math/latex.md
      - BLOG/Math/linear.md
      - BLOG/Math/taylor.md
      - BLOG/Math/max-pr.md
      - BLOG/Math/sympy-det.md
    - 物理:
      - BLOG/Physics/guass-stokes.md
      - BLOG/Physics/electromagnetics.md
    - 电子工程:
      - BLOG/ElectronicEngineering/verilog-simulation.md
      - BLOG/ElectronicEngineering/storage.md
      - BLOG/ElectronicEngineering/rlc.md
      - BLOG/ElectronicEngineering/yosys-try.md
    - FPGA:
      - BLOG/Fpga/compare.md
    - 日语:
      - BLOG/Japanese/notes-2202-2203.md
      - BLOG/Japanese/notes-2204.md
      - BLOG/Japanese/notes-2205.md
      - BLOG/Japanese/verb.md
      - BLOG/Japanese/adj.md
      - BLOG/Japanese/noun.md
      - BLOG/Japanese/grammar.md
      - BLOG/Japanese/essays.md
      - BLOG/Japanese/tantanmen-translation.md
      - BLOG/Japanese/chinese.md
    - 游戏:
      - BLOG/Game/what-is-game.md
      - BLOG/Game/2d-vs-3d.md
      - BLOG/Game/controller.md
    - 其他:
      - BLOG/Others/video-info.md
      - BLOG/Others/sony-extend.md
  - 开发:
    - DEV/index.md
    - DEV/interests.md
    - React:
      - DEV/React/h5.md
      - DEV/React/notes.md
      - DEV/React/vite.md
    - Three:
      - DEV/Three/setup.md
    - WebGPU:
      - DEV/Webgpu/notes.md
      - DEV/Webgpu/first-triangle.md
    - SwiftUI:
      - DEV/SwiftUI/data-essentials.md
    - Flutter:
      - DEV/Flutter/commands.md
      - DEV/Flutter/template.md
      - DEV/Flutter/dart-lint.md
      - DEV/Flutter/state-management.md
      - DEV/Flutter/web-consideration.md
    - 编程:
      - DEV/Programming/recommendation.md
      - DEV/Programming/my-feelings.md
      - C:
        - DEV/Programming/C/review.md
        - DEV/Programming/C/final.md
        - DEV/Programming/C/stdout-fflush.md
        - DEV/Programming/C/watch-matrix.md
      - Python:
        - DEV/Programming/Python/copy.md
        - DEV/Programming/Python/numpy-overview.md
      - Swift:
        - DEV/Programming/Swift/learning-resources.md
        - DEV/Programming/Swift/notes-basic-grammars.md
        - DEV/Programming/Swift/notes-language-guide.md
        - DEV/Programming/Swift/notes-useful-foundation.md
        - DEV/Programming/Swift/lecture-homework.md
        - DEV/Programming/Swift/parallel-for.md
      - Dart:
        - DEV/Programming/Dart/learning.md
      - Cpp:
        - DEV/Programming/Cpp/1.md
        - DEV/Programming/Cpp/2.md
        - DEV/Programming/Cpp/3.md
        - DEV/Programming/Cpp/4.md
        - DEV/Programming/Cpp/5.md
        - DEV/Programming/Cpp/6.md
        - DEV/Programming/Cpp/7.md
        - DEV/Programming/Cpp/8.md
        - DEV/Programming/Cpp/google-format.md
        - DEV/Programming/Cpp/class-properties.md
        - DEV/Programming/Cpp/list.md
        - DEV/Programming/Cpp/stack.md
        - DEV/Programming/Cpp/final.md
        - DEV/Programming/Cpp/oj.md
  - 研究:
    - RESEARCH/index.md
    - CG:
      - RESEARCH/CG/games101.md
      - RESEARCH/CG/tiger-book.md
      - RESEARCH/CG/blender-donut.md
      - RESEARCH/CG/blender-manual.md
      - RESEARCH/CG/games203.md
      - RESEARCH/CG/games105.md
      - RESEARCH/CG/format.md
      - RESEARCH/CG/format-usdz.md
    - GPU:
      - RESEARCH/Gpu/gpu.md
      - RESEARCH/Gpu/cuda.md
  - 二次元:
    - 2/index.md
    - 番:
      - 2/Anime/anime-rating.md
      - 2/Anime/anime-rating-extraordinary.md
      - 2/Anime/anime-rating-great.md
      - 2/Anime/anime-rating-good.md
    - 喜欢的:
      - 2/Sukina/pictures.md
      - 2/Sukina/kawaii.md
      - 2/Sukina/kawaii-koe.md
      - 2/Sukina/artists.md
      - 2/Sukina/vtuber.md
      - 2/Sukina/voice.md
    - Galgame:
      - 2/Galgame/ddlc.md
    - 原神:
      - 2/Games/Genshin/characters.md
      - 2/Games/Genshin/graphic-quality.md
      - 2/Games/Genshin/controller.md
      - 2/Games/Genshin/food.md
    - Apex:
      - 2/Games/Apex/controller-aim.md
      - 2/Games/Apex/controller-settings.md
      - 2/Games/Apex/zhidong-settings.md
      - 2/Games/Apex/key-mouse-settings.md
      - 2/Games/Apex/characters.md
      - 2/Games/Apex/17.md
  - 随笔:
    - ESSAY/index.md
    - 随笔记:
      - ESSAY/Jottings/2312.md
      - ESSAY/Jottings/2311.md
      - ESSAY/Jottings/2310.md
      - ESSAY/Jottings/2309.md
      - ESSAY/Jottings/2308.md
      - ESSAY/Jottings/2307.md
      - ESSAY/Jottings/2306.md
      - ESSAY/Jottings/2305.md
      - ESSAY/Jottings/2304.md
      - ESSAY/Jottings/2303.md
      - ESSAY/Jottings/2302.md
      - ESSAY/Jottings/2301.md
      - ESSAY/Jottings/2211-2212.md
      - ESSAY/Jottings/2209-2210.md
      - ESSAY/Jottings/2207-2208.md
      - ESSAY/Jottings/2205-2206.md
      - ESSAY/Jottings/2203-2204.md
      - ESSAY/Jottings/2201-2202.md
      - ESSAY/Jottings/2111-2112.md
      - ESSAY/Jottings/2109-2110.md
      - ESSAY/Jottings/2107-2108.md
      - ESSAY/Jottings/2105-2106.md
      - ESSAY/Jottings/2103-2104.md
      - ESSAY/Jottings/2101-2102.md
      - ESSAY/Jottings/2011-2012.md
      - ESSAY/Jottings/2009-2010.md
      - ESSAY/Jottings/2007-2008.md
      - ESSAY/Jottings/2005-2006.md
      - ESSAY/Jottings/2003-2004.md
      - ESSAY/Jottings/2001-2002.md
      - ESSAY/Jottings/0.md
      - ESSAY/Jottings/1906-1912.md
      - ESSAY/Jottings/1807-1812.md
      - ESSAY/Jottings/1801-1806.md
      - ESSAY/Jottings/17.md
      - ESSAY/Jottings/16.md
    - 文章:
      - ESSAY/Articles/231211-life-targets.md
      - ESSAY/Articles/231018-research.md
      - ESSAY/Articles/230629-account-book.md
      - ESSAY/Articles/230403-buy-phone.md
      - ESSAY/Articles/230305-cccc-memory.md
      - ESSAY/Articles/221227-expressvpn-refund.md
      - ESSAY/Articles/220921-upgrade-introduction.md
      - ESSAY/Articles/220715-macbook-story.md
      - ESSAY/Articles/220624-gratitude.md
      - ESSAY/Articles/220621-bytedance-interview.md
      - ESSAY/Articles/220612-reply.md
      - ESSAY/Articles/2205-good-games.md
      - ESSAY/Articles/220506-stop-jianshu.md
      - ESSAY/Articles/220505-library-thu.md
      - ESSAY/Articles/220415-interestx2.md
      - ESSAY/Articles/220410-job-discussion.md
      - ESSAY/Articles/220410-independence.md
      - ESSAY/Articles/220408-appreciating-girl.md
      - ESSAY/Articles/220402-languages-comparision.md
      - ESSAY/Articles/220324-thoughts-996.md
      - ESSAY/Articles/220107-want-to-be.md
      - ESSAY/Articles/211104-emotion-bad.md
      - ESSAY/Articles/210928-apple-recruitment-share.md
      - ESSAY/Articles/2109-covid-influence.md
      - ESSAY/Articles/2109-group-clear.md
      - ESSAY/Articles/210820-cccc-event.md
      - ESSAY/Articles/210801-affection-3.md
      - ESSAY/Articles/210519-app-dev-experience.md
      - ESSAY/Articles/210516-apple-education-address.md
      - ESSAY/Articles/210502-extend-your-way.md
      - ESSAY/Articles/201119-a-new-review.md
      - ESSAY/Articles/201213-look-at-yourself.md
      - ESSAY/Articles/200916-my-pursue.md
      - ESSAY/Articles/200713-sutuo-and-me.md
      - ESSAY/Articles/200703-talk-with-junior.md
      - ESSAY/Articles/200607-gaokao-memory.md
      - ESSAY/Articles/200604-small-goal.md
      - ESSAY/Articles/200602-tennkinoko.md
      - ESSAY/Articles/200506-why.md
      - ESSAY/Articles/2005-travel.md
      - ESSAY/Articles/190730-tangyan-rd-23.md
      - ESSAY/Articles/190723-feelings-in-6-days.md
      - ESSAY/Articles/190707-address-to-nonlocal-students.md
      - ESSAY/Articles/190629-affection-2.md
      - ESSAY/Articles/1905-non-intelligent.md
      - ESSAY/Articles/1901-go-to-thu.md
      - ESSAY/Articles/1811-do-it.md
      - ESSAY/Articles/1808-ideality-and-reality.md
      - ESSAY/Articles/1806-apply-thu.md
      - ESSAY/Articles/18-tree.md
      - ESSAY/Articles/18-what-i-love.md
      - ESSAY/Articles/17-dream-2017.md
      - ESSAY/Articles/14-affection-1.md
  - 转载:
    - REPRODUCE/index.md
    - 演讲:
      - REPRODUCE/speech/tim-cook-at-duke.md
    - 摘录:
      - REPRODUCE/book/harford-occupation-choice.md
      - REPRODUCE/book/the-long-view.md
    - 文章:
      - REPRODUCE/article/proses.md
      - REPRODUCE/article/my-best-teacher.md
    - 博客:
      - REPRODUCE/blog/how-to-ask-questions-the-smart-way.md
    - 歌词:
      - REPRODUCE/lyrics/watagumo.md
    - 诗:
      - REPRODUCE/poem/poems.md
  - 网站:
    # 访客打开网站第一个看到的是 docs/index.md
    # 构建网站时，不用管报错 "The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md"
    # 如果访客之后想要重新看到这个界面，可以在 docs/WEBSITE/index.md 找到
    - WEBSITE/index.md
    - WEBSITE/build.md
    - WEBSITE/help.md
    - WEBSITE/test.md

# [UI]
# [top]
theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Yang-Xijie/yang-xijie.github.io
repo_name: yang-xijie.github.io
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: 杨希杰 CC-BY-4.0
# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | Yang-Xijie
      icon: fontawesome/brands/github
      link: https://github.com/Yang-Xijie
    - name: Bilibili | 杨希杰619
      icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
    - name: 小杰答疑群 QQ 796233390
      icon: fontawesome/brands/qq
      link: https://yang-xijie.github.io/ME/qq-groups/
    - name: 小杰水群 QQ 824114857
      icon: fontawesome/brands/qq
      link: https://yang-xijie.github.io/ME/qq-groups/
    - name: 小红书 | 杨希杰
      icon: fontawesome/solid/images
      link: https://www.xiaohongshu.com/user/profile/61be0cc10000000021024369
    - name: 打赏支持
      icon: fontawesome/solid/mug-saucer
      link: https://yang-xijie.github.io/ME/support/

# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
